import { RevisionSheetData, GenerationSettings } from '../types';

/**
 * This is a placeholder for a local AI service.
 * It is not currently used in the application but is provided to resolve build errors.
 * It returns mock data to simulate a successful API call.
 */

export const generateRevisionSheet = async (
  documentText: string,
  settings: GenerationSettings
): Promise<RevisionSheetData> => {
  console.log('Using local AI service for generation...', { documentText: documentText.substring(0, 100), settings });
  // Simulate a network delay
  await new Promise(resolve => setTimeout(resolve, 1500));

  const language = settings.language ?? 'en';
  const localized = {
    title: language === 'fr' ? 'Fiche de revision simulee (locale)' : 'Mock Revision Sheet (Local)',
    introTitle: language === 'fr' ? 'Introduction generee localement' : 'Introduction from Local AI',
    introContent: language === 'fr'
      ? 'Ceci est un contenu fictif genere par le service local. Il simule un apercu de base d un document.'
      : 'This is mock content generated by the local service. It simulates a basic overview of a document.',
    keyTitle: language === 'fr' ? 'Points cles generes localement' : 'Key Concepts from Local AI',
    keyContent: language === 'fr'
      ? '* Ceci est un point fictif.\n* Ceci est un autre point fictif.\n\n!imp[Ceci est un fait important simule.]'
      : '* This is a mock bullet point.\n* This is another mock bullet point.\n\n!imp[This is an important mock fact.]'
  };

  return {
    title: localized.title,
    sections: [
      {
        id: 'local-sec-1',
        title: localized.introTitle,
        content: localized.introContent,
      },
      {
        id: 'local-sec-2',
        title: localized.keyTitle,
        content: localized.keyContent,
      },
    ],
  };
};

export const refineRevisionSheet = async (
  currentSheet: RevisionSheetData,
  refinementPrompt: string,
  documentText: string,
  settings: GenerationSettings
): Promise<RevisionSheetData> => {
    console.log('Using local AI service for refinement...', { refinementPrompt, documentText: documentText.substring(0, 100), settings });
    await new Promise(resolve => setTimeout(resolve, 1000));

    const language = settings.language ?? 'en';
    const newSection = {
        id: `local-refined-${Date.now()}`,
        title: language === 'fr' ? `Affinage : ${refinementPrompt}` : `Refined: ${refinementPrompt}`,
        content: language === 'fr'
            ? `Cette section a ete ajoutee selon votre demande : "${refinementPrompt}"`
            : `This section was added based on your request: "${refinementPrompt}"`
    };

    return {
        ...currentSheet,
        sections: [...currentSheet.sections, newSection]
    };
};
